package co.ke.xently.common.utils


const val ENCRYPTED_SHARED_PREFERENCE_KEY = "ENCRYPTED_SHARED_PREFERENCE_KEY"
const val UNENCRYPTED_SHARED_PREFERENCE_KEY = "UNENCRYPTED_SHARED_PREFERENCE_KEY"
const val TOKEN_VALUE_SHARED_PREFERENCE_KEY = "TOKEN_VALUE_SHARED_PREFERENCE_KEY"